use serde_json::{Value, json};

#[derive(Clone, Copy)]
pub(crate) struct Scenario {
    pub(crate) id: &'static str,
    pub(crate) title: &'static str,
    pub(crate) purpose: &'static str,
    pub(crate) query: &'static str,
    pub(crate) extension: &'static str,
}

const SCENARIOS: &[Scenario] = &[
    Scenario {
        id: "hwp-type",
        title: "HWP 문서만 찾기",
        purpose: "한글 문서 형식별 검색",
        query: "hwp",
        extension: ".hwp",
    },
    Scenario {
        id: "hwpx-type",
        title: "HWPX 문서만 찾기",
        purpose: "한글 신형 문서 형식별 검색",
        query: "hwpx",
        extension: ".hwpx",
    },
    Scenario {
        id: "pdf-type",
        title: "PDF 문서 찾기",
        purpose: "PDF 파일 형식별 검색",
        query: "pdf",
        extension: ".pdf",
    },
    Scenario {
        id: "office-type",
        title: "오피스 문서 찾기",
        purpose: "문서 확장자와 내용 검색",
        query: "docx pptx xlsx",
        extension: ".docx,.pptx,.xlsx",
    },
    Scenario {
        id: "markdown-type",
        title: "Markdown 메모 찾기",
        purpose: "개발 문서와 메모 검색",
        query: "md",
        extension: ".md",
    },
    Scenario {
        id: "text-type",
        title: "텍스트 파일 찾기",
        purpose: "plain text 파일 검색",
        query: "txt",
        extension: ".txt",
    },
    Scenario {
        id: "government",
        title: "범정부 문서 찾기",
        purpose: "범정부 관련 문서 검색",
        query: "범정부",
        extension: "",
    },
    Scenario {
        id: "government-hwp",
        title: "범정부 HWP 찾기",
        purpose: "범정부 한글 문서 검색",
        query: "범정부 hwp",
        extension: ".hwp",
    },
    Scenario {
        id: "contract",
        title: "계약서 찾기",
        purpose: "계약·협약 문서 검색",
        query: "계약",
        extension: "",
    },
    Scenario {
        id: "proposal",
        title: "제안서 찾기",
        purpose: "사업 제안서 검색",
        query: "제안서",
        extension: "",
    },
    Scenario {
        id: "invoice",
        title: "세금계산서 찾기",
        purpose: "회계 증빙 검색",
        query: "세금계산서",
        extension: "",
    },
    Scenario {
        id: "report",
        title: "보고서 찾기",
        purpose: "주간·월간 보고서 검색",
        query: "보고서",
        extension: "",
    },
    Scenario {
        id: "meeting",
        title: "회의 기록 찾기",
        purpose: "회의록과 Meet 기록 검색",
        query: "회의",
        extension: "",
    },
    Scenario {
        id: "presentation",
        title: "발표자료 찾기",
        purpose: "발표자료 검색",
        query: "발표",
        extension: "",
    },
    Scenario {
        id: "data",
        title: "데이터 문서 찾기",
        purpose: "데이터·모델·품질 문서 검색",
        query: "데이터",
        extension: "",
    },
    Scenario {
        id: "api",
        title: "API 문서 찾기",
        purpose: "API·개발 문서 검색",
        query: "api",
        extension: "",
    },
    Scenario {
        id: "rust",
        title: "Rust 코드 찾기",
        purpose: "Rust 소스 검색",
        query: "rust",
        extension: ".rs",
    },
    Scenario {
        id: "python",
        title: "Python 코드 찾기",
        purpose: "Python 소스 검색",
        query: "python",
        extension: ".py",
    },
    Scenario {
        id: "javascript",
        title: "JavaScript 코드 찾기",
        purpose: "JavaScript 소스 검색",
        query: "javascript",
        extension: ".js",
    },
    Scenario {
        id: "config",
        title: "설정 파일 찾기",
        purpose: "환경설정과 구성 검색",
        query: "config",
        extension: "",
    },
    Scenario {
        id: "security",
        title: "보안 문서 찾기",
        purpose: "보안·개인정보 문서 검색",
        query: "보안",
        extension: "",
    },
    Scenario {
        id: "privacy",
        title: "개인정보 문서 찾기",
        purpose: "개인정보 처리 문서 검색",
        query: "개인정보",
        extension: "",
    },
    Scenario {
        id: "ai",
        title: "AI 문서 찾기",
        purpose: "AI·머신러닝 자료 검색",
        query: "AI",
        extension: "",
    },
    Scenario {
        id: "rag",
        title: "RAG 문서 찾기",
        purpose: "검색증강생성 자료 검색",
        query: "RAG",
        extension: "",
    },
    Scenario {
        id: "healthcare",
        title: "헬스케어 자료 찾기",
        purpose: "헬스케어 프로젝트 검색",
        query: "헬스케어",
        extension: "",
    },
    Scenario {
        id: "education",
        title: "교육 자료 찾기",
        purpose: "강의·교육자료 검색",
        query: "강의",
        extension: "",
    },
    Scenario {
        id: "research",
        title: "연구자료 찾기",
        purpose: "논문·연구자료 검색",
        query: "연구",
        extension: "",
    },
    Scenario {
        id: "finance",
        title: "재무자료 찾기",
        purpose: "재무·예산 자료 검색",
        query: "예산",
        extension: "",
    },
    Scenario {
        id: "hr",
        title: "인사자료 찾기",
        purpose: "인사·근무 문서 검색",
        query: "근무",
        extension: "",
    },
    Scenario {
        id: "legal",
        title: "법무자료 찾기",
        purpose: "법률·법무 문서 검색",
        query: "법무",
        extension: "",
    },
    Scenario {
        id: "backup",
        title: "백업 사본 찾기",
        purpose: "백업 폴더의 자료 검색",
        query: "백업",
        extension: "",
    },
    Scenario {
        id: "recent",
        title: "최근 작업 찾기",
        purpose: "최근 생성 자료 검색",
        query: "2026",
        extension: "",
    },
    Scenario {
        id: "old",
        title: "과거 자료 찾기",
        purpose: "연도 기반 과거자료 검색",
        query: "2024",
        extension: "",
    },
    Scenario {
        id: "filename",
        title: "파일명으로 찾기",
        purpose: "정확한 파일명 단서 검색",
        query: "정관",
        extension: "",
    },
    Scenario {
        id: "folder",
        title: "폴더 단서로 찾기",
        purpose: "폴더명과 경로 단서 검색",
        query: "문서백업",
        extension: "",
    },
    Scenario {
        id: "person",
        title: "사람 이름으로 찾기",
        purpose: "작성자·담당자 단서 검색",
        query: "cheol",
        extension: "",
    },
    Scenario {
        id: "company",
        title: "회사 이름으로 찾기",
        purpose: "회사·기관 자료 검색",
        query: "마커",
        extension: "",
    },
    Scenario {
        id: "project",
        title: "프로젝트 자료 찾기",
        purpose: "프로젝트명 단서 검색",
        query: "프로젝트",
        extension: "",
    },
    Scenario {
        id: "topic",
        title: "주제어로 찾기",
        purpose: "자연어 주제 검색",
        query: "공통기반",
        extension: "",
    },
    Scenario {
        id: "mixed-format",
        title: "주제와 형식 함께 찾기",
        purpose: "주제어와 확장자 조합",
        query: "공통기반 hwp",
        extension: ".hwp",
    },
    Scenario {
        id: "short-query",
        title: "짧은 검색어 찾기",
        purpose: "짧은 단어의 인덱스 검색",
        query: "AI",
        extension: "",
    },
    Scenario {
        id: "korean",
        title: "한글 자연어 검색",
        purpose: "한국어 문장형 검색",
        query: "사업 수행 계획",
        extension: "",
    },
    Scenario {
        id: "english",
        title: "영문 자연어 검색",
        purpose: "영문 키워드 검색",
        query: "project proposal",
        extension: "",
    },
    Scenario {
        id: "archive",
        title: "압축자료 찾기",
        purpose: "압축파일과 내부 단서 검색",
        query: "zip",
        extension: ".zip",
    },
    Scenario {
        id: "email",
        title: "이메일 자료 찾기",
        purpose: "메일 파일 검색",
        query: "email",
        extension: ".eml",
    },
    Scenario {
        id: "image",
        title: "이미지 자료 찾기",
        purpose: "이미지 메타데이터 검색",
        query: "png",
        extension: ".png",
    },
    Scenario {
        id: "media",
        title: "미디어 자료 찾기",
        purpose: "동영상·음성 자료 검색",
        query: "mp4",
        extension: ".mp4",
    },
    Scenario {
        id: "duplicate",
        title: "중복 자료 후보 찾기",
        purpose: "백업·중복 단서 검색",
        query: "copy",
        extension: "",
    },
    Scenario {
        id: "unindexed",
        title: "인덱스 확인용 검색",
        purpose: "검색 결과와 인덱스 상태 점검",
        query: "문서",
        extension: "",
    },
    Scenario {
        id: "content",
        title: "본문 내용으로 찾기",
        purpose: "파일명에 없는 본문 단서 검색",
        query: "payment terms",
        extension: "",
    },
    Scenario {
        id: "metadata",
        title: "메타데이터로 찾기",
        purpose: "제목·요약·경로 단서 검색",
        query: "한글 문서",
        extension: "",
    },
    Scenario {
        id: "root-documents",
        title: "Documents 범위 검색",
        purpose: "Documents 루트 중심 검색",
        query: "문서",
        extension: "",
    },
    Scenario {
        id: "root-downloads",
        title: "Downloads 범위 검색",
        purpose: "Downloads 루트 중심 검색",
        query: "백업",
        extension: "",
    },
    Scenario {
        id: "root-drive",
        title: "GoogleDrive 범위 검색",
        purpose: "Drive 문서 중심 검색",
        query: "논문",
        extension: "",
    },
    Scenario {
        id: "root-project",
        title: "프로젝트 루트 검색",
        purpose: "Jikji 프로젝트 자체 검색",
        query: "discover",
        extension: ".rs",
    },
    Scenario {
        id: "strategy-lexical",
        title: "정밀 키워드 검색",
        purpose: "Jikji lexical 전략 결과 확인",
        query: "계약서",
        extension: "",
    },
    Scenario {
        id: "strategy-anchors",
        title: "파일명 앵커 검색",
        purpose: "파일명·경로 앵커 결과 확인",
        query: "제안서",
        extension: "",
    },
    Scenario {
        id: "strategy-semantic",
        title: "의미 기반 검색",
        purpose: "본문 의미 단서 검색",
        query: "사업을 시작하기 위한 문서",
        extension: "",
    },
    Scenario {
        id: "strategy-advanced",
        title: "고급 검색",
        purpose: "여러 검색 전략 병합 결과 확인",
        query: "범정부 데이터",
        extension: "",
    },
    Scenario {
        id: "judge",
        title: "Judge 후보 검토",
        purpose: "merged candidate slate와 judge 상태 확인",
        query: "핵심 제안서",
        extension: "",
    },
    Scenario {
        id: "preview-hwp",
        title: "HWP 미리보기",
        purpose: "HWP 선택 후 렌더링 확인",
        query: "hwp",
        extension: ".hwp",
    },
    Scenario {
        id: "preview-pdf",
        title: "PDF 미리보기",
        purpose: "PDF 선택 후 렌더링 확인",
        query: "pdf",
        extension: ".pdf",
    },
    Scenario {
        id: "preview-office",
        title: "Office 미리보기",
        purpose: "Office 선택 후 렌더링 확인",
        query: "docx",
        extension: ".docx",
    },
];

pub(crate) fn list() -> Value {
    json!({"count": SCENARIOS.len(), "scenarios": SCENARIOS.iter().map(|s| json!({"id":s.id,"title":s.title,"purpose":s.purpose,"query":s.query,"extension":s.extension})).collect::<Vec<_>>()})
}

pub(crate) fn get(id: &str) -> Option<Scenario> {
    SCENARIOS.iter().copied().find(|scenario| scenario.id == id)
}
